spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oaga1xidp8nSjGBc0h7
            client-secret: _1sGqnOISKYA0OShQX36kuspNnsbvDfq5pa4iMxB
            scope: openid email profile
        provider:
          okta:
            issuer-uri: https://dev-507183.oktapreview.com/oauth2/default
  profiles:
    active: @spring.profiles.active@